name: Deploy
on: [push]
jobs:
    deploy_site1:
        runs-on: ubuntu-latest

        steps:
            -   name: checkout_site1
                uses: actions/checkout@v6

            -   name: docker_build
                run: docker build -t site1 ./site1
            
            -   name: docker_run
                run: docker run -d -p 8080:80 site1

            -   name: Wait for container 1 to be healthy
                run: |
                    until curl -sf http://localhost:8080 > /dev/null; do
                        echo "waiting..."
                        sleep 1
                        done
            
            -   name: Checks HMTL5
                uses: Cyb3r-Jak3/html5validator-action@7.2.0
                with:
                    root: ./site1
                

    deploy_site2:
        runs-on: ubuntu-latest

        steps:
            -   name: checkout_site2
                uses: actions/checkout@v6

            -   name: docker_build
                run: docker build -t site2 ./site2

            -   name: docker_run
                run: docker run -d -p 8081:80 site2
            
            -   name: Wait for container 2 to be healthy
                run: |
                    until curl -sf http://localhost:8081 > /dev/null; do
                        echo "waiting..."
                        sleep 1
                        done

            -   name: Checks HTML5
                uses: Cyb3r-Jak3/html5validator-action@7.2.0
                with:
                    root: ./site2
            