name: Deploy
on: [push]
jobs:
    deploy_site1:
        runs-on: ubuntu-latest

        steps:
            -   name: checkout_site1
                uses: actions/checkout@v6

            -   name: print_helloWorld
                run: echo "Hello World"
            