name: Deploy
on:
    push:
        branches: ["main"]
jobs:
    Deploy:
        
        runs-on: ubuntu-latest
        timeout-minutes: 10
        
        steps:
            -   name: Tailscale ping test
                uses: tailscale/github-action@v4
                with:
                    oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
                    oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
                    tags: tag:ci
                    ping: ${{ secrets.TAILSCALE_IP }}
            
            -   name: Deploy via SSH
                uses: appleboy/ssh-action@1.2.5
                with:
                    host: ${{ secrets.TAILSCALE_IP }}
                    username: ${{ secrets.SSH_USER }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    script: |
                       cd ${{ secrets.DEPLOY_PATH }}
                       git pull
                       docker compose build nginx-site1
                       docker compose up -d nginx-site1
                       docker compose build nginx-site2
                       docker compose up -d nginx-site2